/*
 * EasySendSMSAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package app.easysendsms.restapi.controllers;

import app.easysendsms.restapi.EasySendSMSAPIClient;
import app.easysendsms.restapi.Environment;
import app.easysendsms.restapi.authentication.CustomHeaderAuthenticationModel;
import app.easysendsms.restapi.testing.HttpCallbackCatcher;
import org.junit.AfterClass;
import org.junit.BeforeClass;
import org.junit.Rule;
import org.junit.rules.Timeout;

/**
 * Base class for all test cases.
 */
public class BaseControllerTest {
    /**
     * Test configuration.
     */
    public static final int REQUEST_TIMEOUT = 30;

    public static final double ASSERT_PRECISION = 0.01;
    
    /**
     * Global rules for tests.
     */
    @Rule
    public Timeout globalTimeout = Timeout.seconds(REQUEST_TIMEOUT);
    
    /**
     * Test fixtures,
     * Used to serve as HttpCallback and to capture request & response.
     */

    protected static HttpCallbackCatcher httpResponse;
    
    /**
     * Setup test.
     */
    @BeforeClass
    public static void setUp() throws Exception {
        httpResponse = new HttpCallbackCatcher(); 
    }

    /**
     * Tear down test.
     */
    @AfterClass
    public static void tearDown() throws Exception {
        httpResponse = null;
    }

    /**
     * Create test configuration from Environment variables.
     */
    protected static EasySendSMSAPIClient createConfigurationFromEnvironment() {
        EasySendSMSAPIClient.Builder builder = new EasySendSMSAPIClient.Builder();

        final String environment = System.getenv("EASY_SEND_SMSAPI_LIB_ENVIRONMENT");
        final String timeout = System.getenv("EASY_SEND_SMSAPI_LIB_TIMEOUT");
        final String apikey = System.getenv("EASY_SEND_SMSAPI_LIB_APIKEY");

        if (apikey != null) {
            builder.customHeaderAuthenticationCredentials(new CustomHeaderAuthenticationModel
                    .Builder(apikey)
                    .build());
        }
        if (environment != null) {
            builder.environment(Environment.fromString(environment));
        }
        if (timeout != null) {
            builder.httpClientConfig(configBuilder -> configBuilder.timeout(
                    Long.parseLong(timeout)));
        }
        return builder.build();
    }

    
    /**
     * Create test configuration.
     */
    protected static EasySendSMSAPIClient createConfiguration() {
        // Set Configuration parameters for test execution
        EasySendSMSAPIClient config = createConfigurationFromEnvironment();
        config = config.newBuilder()
                .httpCallback(httpResponse)
                .build();
        return config;
    }
}
