/*
 * EasySendSMSAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package app.easysendsms.restapi.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for BalanceResponse type.
 */
public class BalanceResponse {
    private Integer balance;

    /**
     * Default constructor.
     */
    public BalanceResponse() {
    }

    /**
     * Initialization constructor.
     * @param  balance  Integer value for balance.
     */
    public BalanceResponse(
            Integer balance) {
        this.balance = balance;
    }

    /**
     * Getter for Balance.
     * @return Returns the Integer
     */
    @JsonGetter("balance")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getBalance() {
        return balance;
    }

    /**
     * Setter for Balance.
     * @param balance Value for Integer
     */
    @JsonSetter("balance")
    public void setBalance(Integer balance) {
        this.balance = balance;
    }

    /**
     * Converts this BalanceResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "BalanceResponse [" + "balance=" + balance + "]";
    }

    /**
     * Builds a new {@link BalanceResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link BalanceResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .balance(getBalance());
        return builder;
    }

    /**
     * Class to build instances of {@link BalanceResponse}.
     */
    public static class Builder {
        private Integer balance;



        /**
         * Setter for balance.
         * @param  balance  Integer value for balance.
         * @return Builder
         */
        public Builder balance(Integer balance) {
            this.balance = balance;
            return this;
        }

        /**
         * Builds a new {@link BalanceResponse} object using the set fields.
         * @return {@link BalanceResponse}
         */
        public BalanceResponse build() {
            return new BalanceResponse(balance);
        }
    }
}
