/*
 * EasySendSMSAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package app.easysendsms.restapi.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for HlrQueryRequest type.
 */
public class HlrQueryRequest {
    private String number;

    /**
     * Default constructor.
     */
    public HlrQueryRequest() {
    }

    /**
     * Initialization constructor.
     * @param  number  String value for number.
     */
    public HlrQueryRequest(
            String number) {
        this.number = number;
    }

    /**
     * Getter for Number.
     * Subscriber's MSISDN to be checked. Multiple numbers can be queried using commas, max 30 per
     * request.
     * @return Returns the String
     */
    @JsonGetter("number")
    public String getNumber() {
        return number;
    }

    /**
     * Setter for Number.
     * Subscriber's MSISDN to be checked. Multiple numbers can be queried using commas, max 30 per
     * request.
     * @param number Value for String
     */
    @JsonSetter("number")
    public void setNumber(String number) {
        this.number = number;
    }

    /**
     * Converts this HlrQueryRequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "HlrQueryRequest [" + "number=" + number + "]";
    }

    /**
     * Builds a new {@link HlrQueryRequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link HlrQueryRequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(number);
        return builder;
    }

    /**
     * Class to build instances of {@link HlrQueryRequest}.
     */
    public static class Builder {
        private String number;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  number  String value for number.
         */
        public Builder(String number) {
            this.number = number;
        }

        /**
         * Setter for number.
         * @param  number  String value for number.
         * @return Builder
         */
        public Builder number(String number) {
            this.number = number;
            return this;
        }

        /**
         * Builds a new {@link HlrQueryRequest} object using the set fields.
         * @return {@link HlrQueryRequest}
         */
        public HlrQueryRequest build() {
            return new HlrQueryRequest(number);
        }
    }
}
