/*
 * EasySendSMSAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package app.easysendsms.restapi.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.Map;

/**
 * This is a model class for HlrQueryResponse type.
 */
public class HlrQueryResponse {
    private Map<String, Responses> responses;

    /**
     * Default constructor.
     */
    public HlrQueryResponse() {
    }

    /**
     * Initialization constructor.
     * @param  responses  Map of String, value for responses.
     */
    public HlrQueryResponse(
            Map<String, Responses> responses) {
        this.responses = responses;
    }

    /**
     * Getter for Responses.
     * @return Returns the Map of String, Responses
     */
    @JsonGetter("responses")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Map<String, Responses> getResponses() {
        return responses;
    }

    /**
     * Setter for Responses.
     * @param responses Value for Map of String, Responses
     */
    @JsonSetter("responses")
    public void setResponses(Map<String, Responses> responses) {
        this.responses = responses;
    }

    /**
     * Converts this HlrQueryResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "HlrQueryResponse [" + "responses=" + responses + "]";
    }

    /**
     * Builds a new {@link HlrQueryResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link HlrQueryResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .responses(getResponses());
        return builder;
    }

    /**
     * Class to build instances of {@link HlrQueryResponse}.
     */
    public static class Builder {
        private Map<String, Responses> responses;



        /**
         * Setter for responses.
         * @param  responses  Map of String, value for responses.
         * @return Builder
         */
        public Builder responses(Map<String, Responses> responses) {
            this.responses = responses;
            return this;
        }

        /**
         * Builds a new {@link HlrQueryResponse} object using the set fields.
         * @return {@link HlrQueryResponse}
         */
        public HlrQueryResponse build() {
            return new HlrQueryResponse(responses);
        }
    }
}
