/*
 * EasySendSMSAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package app.easysendsms.restapi.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for NvQueryRequest type.
 */
public class NvQueryRequest {
    private String number;

    /**
     * Default constructor.
     */
    public NvQueryRequest() {
    }

    /**
     * Initialization constructor.
     * @param  number  String value for number.
     */
    public NvQueryRequest(
            String number) {
        this.number = number;
    }

    /**
     * Getter for Number.
     * Subscriber's MSISDN to be checked. Multiple numbers can be queried using commas, max 30 per
     * request.
     * @return Returns the String
     */
    @JsonGetter("number")
    public String getNumber() {
        return number;
    }

    /**
     * Setter for Number.
     * Subscriber's MSISDN to be checked. Multiple numbers can be queried using commas, max 30 per
     * request.
     * @param number Value for String
     */
    @JsonSetter("number")
    public void setNumber(String number) {
        this.number = number;
    }

    /**
     * Converts this NvQueryRequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "NvQueryRequest [" + "number=" + number + "]";
    }

    /**
     * Builds a new {@link NvQueryRequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link NvQueryRequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(number);
        return builder;
    }

    /**
     * Class to build instances of {@link NvQueryRequest}.
     */
    public static class Builder {
        private String number;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  number  String value for number.
         */
        public Builder(String number) {
            this.number = number;
        }

        /**
         * Setter for number.
         * @param  number  String value for number.
         * @return Builder
         */
        public Builder number(String number) {
            this.number = number;
            return this;
        }

        /**
         * Builds a new {@link NvQueryRequest} object using the set fields.
         * @return {@link NvQueryRequest}
         */
        public NvQueryRequest build() {
            return new NvQueryRequest(number);
        }
    }
}
