/*
 * EasySendSMSAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package app.easysendsms.restapi.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;

/**
 * This is a model class for NvQueryResponse type.
 */
public class NvQueryResponse {
    private List<Validation> validations;

    /**
     * Default constructor.
     */
    public NvQueryResponse() {
    }

    /**
     * Initialization constructor.
     * @param  validations  List of Validation value for validations.
     */
    public NvQueryResponse(
            List<Validation> validations) {
        this.validations = validations;
    }

    /**
     * Getter for Validations.
     * @return Returns the List of Validation
     */
    @JsonGetter("validations")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<Validation> getValidations() {
        return validations;
    }

    /**
     * Setter for Validations.
     * @param validations Value for List of Validation
     */
    @JsonSetter("validations")
    public void setValidations(List<Validation> validations) {
        this.validations = validations;
    }

    /**
     * Converts this NvQueryResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "NvQueryResponse [" + "validations=" + validations + "]";
    }

    /**
     * Builds a new {@link NvQueryResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link NvQueryResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .validations(getValidations());
        return builder;
    }

    /**
     * Class to build instances of {@link NvQueryResponse}.
     */
    public static class Builder {
        private List<Validation> validations;



        /**
         * Setter for validations.
         * @param  validations  List of Validation value for validations.
         * @return Builder
         */
        public Builder validations(List<Validation> validations) {
            this.validations = validations;
            return this;
        }

        /**
         * Builds a new {@link NvQueryResponse} object using the set fields.
         * @return {@link NvQueryResponse}
         */
        public NvQueryResponse build() {
            return new NvQueryResponse(validations);
        }
    }
}
