/*
 * EasySendSMSAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package app.easysendsms.restapi.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;

/**
 * This is a model class for SendSmsResponse type.
 */
public class SendSmsResponse {
    private String status;
    private String scheduled;
    private List<String> messageIds;

    /**
     * Default constructor.
     */
    public SendSmsResponse() {
    }

    /**
     * Initialization constructor.
     * @param  status  String value for status.
     * @param  scheduled  String value for scheduled.
     * @param  messageIds  List of String value for messageIds.
     */
    public SendSmsResponse(
            String status,
            String scheduled,
            List<String> messageIds) {
        this.status = status;
        this.scheduled = scheduled;
        this.messageIds = messageIds;
    }

    /**
     * Getter for Status.
     * @return Returns the String
     */
    @JsonGetter("status")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getStatus() {
        return status;
    }

    /**
     * Setter for Status.
     * @param status Value for String
     */
    @JsonSetter("status")
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * Getter for Scheduled.
     * @return Returns the String
     */
    @JsonGetter("scheduled")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getScheduled() {
        return scheduled;
    }

    /**
     * Setter for Scheduled.
     * @param scheduled Value for String
     */
    @JsonSetter("scheduled")
    public void setScheduled(String scheduled) {
        this.scheduled = scheduled;
    }

    /**
     * Getter for MessageIds.
     * @return Returns the List of String
     */
    @JsonGetter("messageIds")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<String> getMessageIds() {
        return messageIds;
    }

    /**
     * Setter for MessageIds.
     * @param messageIds Value for List of String
     */
    @JsonSetter("messageIds")
    public void setMessageIds(List<String> messageIds) {
        this.messageIds = messageIds;
    }

    /**
     * Converts this SendSmsResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "SendSmsResponse [" + "status=" + status + ", scheduled=" + scheduled
                + ", messageIds=" + messageIds + "]";
    }

    /**
     * Builds a new {@link SendSmsResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link SendSmsResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .status(getStatus())
                .scheduled(getScheduled())
                .messageIds(getMessageIds());
        return builder;
    }

    /**
     * Class to build instances of {@link SendSmsResponse}.
     */
    public static class Builder {
        private String status;
        private String scheduled;
        private List<String> messageIds;



        /**
         * Setter for status.
         * @param  status  String value for status.
         * @return Builder
         */
        public Builder status(String status) {
            this.status = status;
            return this;
        }

        /**
         * Setter for scheduled.
         * @param  scheduled  String value for scheduled.
         * @return Builder
         */
        public Builder scheduled(String scheduled) {
            this.scheduled = scheduled;
            return this;
        }

        /**
         * Setter for messageIds.
         * @param  messageIds  List of String value for messageIds.
         * @return Builder
         */
        public Builder messageIds(List<String> messageIds) {
            this.messageIds = messageIds;
            return this;
        }

        /**
         * Builds a new {@link SendSmsResponse} object using the set fields.
         * @return {@link SendSmsResponse}
         */
        public SendSmsResponse build() {
            return new SendSmsResponse(status, scheduled, messageIds);
        }
    }
}
