/*
 * EasySendSMSAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package app.easysendsms.restapi.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for Validation type.
 */
public class Validation {
    private String msisdn;
    private String status;
    private String country;
    private String iso31662;
    private String cc;
    private String netName;
    private String mcc;
    private String mnc;
    private String operator;
    private String type;
    private String netType;

    /**
     * Default constructor.
     */
    public Validation() {
    }

    /**
     * Initialization constructor.
     * @param  msisdn  String value for msisdn.
     * @param  status  String value for status.
     * @param  country  String value for country.
     * @param  iso31662  String value for iso31662.
     * @param  cc  String value for cc.
     * @param  netName  String value for netName.
     * @param  mcc  String value for mcc.
     * @param  mnc  String value for mnc.
     * @param  operator  String value for operator.
     * @param  type  String value for type.
     * @param  netType  String value for netType.
     */
    public Validation(
            String msisdn,
            String status,
            String country,
            String iso31662,
            String cc,
            String netName,
            String mcc,
            String mnc,
            String operator,
            String type,
            String netType) {
        this.msisdn = msisdn;
        this.status = status;
        this.country = country;
        this.iso31662 = iso31662;
        this.cc = cc;
        this.netName = netName;
        this.mcc = mcc;
        this.mnc = mnc;
        this.operator = operator;
        this.type = type;
        this.netType = netType;
    }

    /**
     * Getter for Msisdn.
     * @return Returns the String
     */
    @JsonGetter("msisdn")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getMsisdn() {
        return msisdn;
    }

    /**
     * Setter for Msisdn.
     * @param msisdn Value for String
     */
    @JsonSetter("msisdn")
    public void setMsisdn(String msisdn) {
        this.msisdn = msisdn;
    }

    /**
     * Getter for Status.
     * @return Returns the String
     */
    @JsonGetter("status")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getStatus() {
        return status;
    }

    /**
     * Setter for Status.
     * @param status Value for String
     */
    @JsonSetter("status")
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * Getter for Country.
     * @return Returns the String
     */
    @JsonGetter("country")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getCountry() {
        return country;
    }

    /**
     * Setter for Country.
     * @param country Value for String
     */
    @JsonSetter("country")
    public void setCountry(String country) {
        this.country = country;
    }

    /**
     * Getter for Iso31662.
     * @return Returns the String
     */
    @JsonGetter("iso3166_2")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getIso31662() {
        return iso31662;
    }

    /**
     * Setter for Iso31662.
     * @param iso31662 Value for String
     */
    @JsonSetter("iso3166_2")
    public void setIso31662(String iso31662) {
        this.iso31662 = iso31662;
    }

    /**
     * Getter for Cc.
     * @return Returns the String
     */
    @JsonGetter("cc")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getCc() {
        return cc;
    }

    /**
     * Setter for Cc.
     * @param cc Value for String
     */
    @JsonSetter("cc")
    public void setCc(String cc) {
        this.cc = cc;
    }

    /**
     * Getter for NetName.
     * @return Returns the String
     */
    @JsonGetter("netName")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getNetName() {
        return netName;
    }

    /**
     * Setter for NetName.
     * @param netName Value for String
     */
    @JsonSetter("netName")
    public void setNetName(String netName) {
        this.netName = netName;
    }

    /**
     * Getter for Mcc.
     * @return Returns the String
     */
    @JsonGetter("mcc")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getMcc() {
        return mcc;
    }

    /**
     * Setter for Mcc.
     * @param mcc Value for String
     */
    @JsonSetter("mcc")
    public void setMcc(String mcc) {
        this.mcc = mcc;
    }

    /**
     * Getter for Mnc.
     * @return Returns the String
     */
    @JsonGetter("mnc")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getMnc() {
        return mnc;
    }

    /**
     * Setter for Mnc.
     * @param mnc Value for String
     */
    @JsonSetter("mnc")
    public void setMnc(String mnc) {
        this.mnc = mnc;
    }

    /**
     * Getter for Operator.
     * @return Returns the String
     */
    @JsonGetter("operator")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getOperator() {
        return operator;
    }

    /**
     * Setter for Operator.
     * @param operator Value for String
     */
    @JsonSetter("operator")
    public void setOperator(String operator) {
        this.operator = operator;
    }

    /**
     * Getter for Type.
     * @return Returns the String
     */
    @JsonGetter("type")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getType() {
        return type;
    }

    /**
     * Setter for Type.
     * @param type Value for String
     */
    @JsonSetter("type")
    public void setType(String type) {
        this.type = type;
    }

    /**
     * Getter for NetType.
     * @return Returns the String
     */
    @JsonGetter("netType")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getNetType() {
        return netType;
    }

    /**
     * Setter for NetType.
     * @param netType Value for String
     */
    @JsonSetter("netType")
    public void setNetType(String netType) {
        this.netType = netType;
    }

    /**
     * Converts this Validation into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Validation [" + "msisdn=" + msisdn + ", status=" + status + ", country=" + country
                + ", iso31662=" + iso31662 + ", cc=" + cc + ", netName=" + netName + ", mcc=" + mcc
                + ", mnc=" + mnc + ", operator=" + operator + ", type=" + type + ", netType="
                + netType + "]";
    }

    /**
     * Builds a new {@link Validation.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Validation.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .msisdn(getMsisdn())
                .status(getStatus())
                .country(getCountry())
                .iso31662(getIso31662())
                .cc(getCc())
                .netName(getNetName())
                .mcc(getMcc())
                .mnc(getMnc())
                .operator(getOperator())
                .type(getType())
                .netType(getNetType());
        return builder;
    }

    /**
     * Class to build instances of {@link Validation}.
     */
    public static class Builder {
        private String msisdn;
        private String status;
        private String country;
        private String iso31662;
        private String cc;
        private String netName;
        private String mcc;
        private String mnc;
        private String operator;
        private String type;
        private String netType;



        /**
         * Setter for msisdn.
         * @param  msisdn  String value for msisdn.
         * @return Builder
         */
        public Builder msisdn(String msisdn) {
            this.msisdn = msisdn;
            return this;
        }

        /**
         * Setter for status.
         * @param  status  String value for status.
         * @return Builder
         */
        public Builder status(String status) {
            this.status = status;
            return this;
        }

        /**
         * Setter for country.
         * @param  country  String value for country.
         * @return Builder
         */
        public Builder country(String country) {
            this.country = country;
            return this;
        }

        /**
         * Setter for iso31662.
         * @param  iso31662  String value for iso31662.
         * @return Builder
         */
        public Builder iso31662(String iso31662) {
            this.iso31662 = iso31662;
            return this;
        }

        /**
         * Setter for cc.
         * @param  cc  String value for cc.
         * @return Builder
         */
        public Builder cc(String cc) {
            this.cc = cc;
            return this;
        }

        /**
         * Setter for netName.
         * @param  netName  String value for netName.
         * @return Builder
         */
        public Builder netName(String netName) {
            this.netName = netName;
            return this;
        }

        /**
         * Setter for mcc.
         * @param  mcc  String value for mcc.
         * @return Builder
         */
        public Builder mcc(String mcc) {
            this.mcc = mcc;
            return this;
        }

        /**
         * Setter for mnc.
         * @param  mnc  String value for mnc.
         * @return Builder
         */
        public Builder mnc(String mnc) {
            this.mnc = mnc;
            return this;
        }

        /**
         * Setter for operator.
         * @param  operator  String value for operator.
         * @return Builder
         */
        public Builder operator(String operator) {
            this.operator = operator;
            return this;
        }

        /**
         * Setter for type.
         * @param  type  String value for type.
         * @return Builder
         */
        public Builder type(String type) {
            this.type = type;
            return this;
        }

        /**
         * Setter for netType.
         * @param  netType  String value for netType.
         * @return Builder
         */
        public Builder netType(String netType) {
            this.netType = netType;
            return this;
        }

        /**
         * Builds a new {@link Validation} object using the set fields.
         * @return {@link Validation}
         */
        public Validation build() {
            return new Validation(msisdn, status, country, iso31662, cc, netName, mcc, mnc,
                    operator, type, netType);
        }
    }
}
